services:
  pstb:
    image: pstb
    build:
      context: .
      dockerfile: ./Dockerfile.development
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", "development"]